### ISSUE TITLE
请问这个 code-push-web 您跑通了吗？

### ISSUE THREAD

**Issue by seuzxh** [aloneszjl/code-push-web#1]
您好，我看了 lisong 的 code-push-web，但是无法跑通，请问您这个可以跑吗？想看看基于 web 来管理 code-push 构建

**Comment by seuzxh** [comment]
经和作者交流，该repo无问题，可以惨遭 code-push.com

**Comment by aloneszjl** [comment]
@seuzxh 用lisong的吧，我这个本来是想改下代码，用nginx代理一下的，服务器只有一个，所以想把访问code-push-web的地址从 domain.com -> domain.com/code-push-web 去访问， 后来发现 有code-push-server 本来就可以登录获取token的，我就没用了哦

**Comment by seuzxh** [comment]
@aloneszjl  恩恩，多谢啦~
